services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/midnight/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/midnight/homepage/images:/app/public/images
    restart: unless-stopped
    env_file:
      - .env
